hoj/hoj/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views
from user import views as user_views
from problems import views as prob_views
from submission import views as sub_views
#from ckeditor_uploader import urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', user_views.home, name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', user_views.signup, name='signup'),
    path('about/', user_views.about_us, name = 'about_us'),
    path('profile/', user_views.profile, name='profile'),
    path('problems/', prob_views.problem_list, name = 'problem_list'),    
    path('problem/<int:pid>/', prob_views.problem_id, name ='problem_id'),
    path('problem/submit/', prob_views.submit_code, name = 'submit'),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

hoj/problems/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from ckeditor_uploader.fields import RichTextUploadingField

#save input, output file to "media/problem <id> / filename" directory
def path_to_save(instance, filename):
    return 'problem {0}/{1}'.format(instance.id, filename)

class Problem(models.Model):
    title = models.CharField(max_length=100, blank=False)
    difficulty = models.CharField(max_length=100)
    tags = ArrayField(models.CharField(max_length=100), blank = True)
    description = RichTextUploadingField()
    sample_input = RichTextUploadingField()
    sample_output = RichTextUploadingField()
    time_limit = ArrayField(models.IntegerField(default = 1)) #different time limit for different languages
    memory_limit = models.IntegerField(default = 256)
    input_file = models.FileField(upload_to = path_to_save)
    output_file = models.FileField(upload_to = path_to_save)
    no_of_submissions = models.IntegerField(default = 0)
    no_of_accepted = models.IntegerField(default = 0)
    
    def __str__(self):
        return str(self.id) + '. ' + self.title
    
	#copied from StackOverflow
    #override the default save for saving the files in designated folder. cause model has not created then. 
    def save(self, *args, **kwargs):
        if self.id is None:
            saved = []
            for f in self.__class__._meta.get_fields():
                if isinstance(f, models.FileField):
                    saved.append((f.name, getattr(self, f.name)))
                    setattr(self, f.name, None)

            super(self.__class__, self).save(*args, **kwargs)

            for name, val in saved:
                setattr(self, name, val)
        super(self.__class__, self).save(*args, **kwargs)

hoj/submission/models.py
from django.db import models
from user.models import UserSignup
from problems.models import Problem

#user submitted code save to "media/user <id>/filename"
def path_to_save(instance, filename):
    return 'user {0}/{1}'.format(instance.user_id.id, filename)

LANG_CHOICES = (
        ('C', 'C'),
        ('C++', 'C++'),
        ('Python', 'Python'),
)
VERDICT_CHOICES =   (
        (0, 'Pending'),
        (1, 'Accepted'),
        (2, 'Wrong Answer'),
        (3, 'Compilation Error'),
        (4, 'Time Limit Exceeded'),
        (5, 'Memory Limit Exceeded'),
        (6, 'Run Time Error'),
)
class Submission(models.Model):
    user_id = models.ForeignKey(UserSignup, on_delete = models.CASCADE)
    problem_id = models.ForeignKey(Problem, on_delete = models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    language = models.CharField(max_length = 10, choices = LANG_CHOICES, default = 'C++')
    verdict = models.IntegerField(choices = VERDICT_CHOICES, default = 0)
    time = models.DecimalField(max_digits=5, decimal_places=3, default = 0.0)
    memory = models.IntegerField(default = 0)
    code = models.FileField(upload_to = path_to_save)

    def __str__(self):
        return str(self.id)
    

hoj/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.postgres.fields import ArrayField

#def path_to_save(instance, filename):
#    return 'user {0}/{1}'.format(instance.user_id.id, filename)

class UserSignup(AbstractUser):
    full_name = models.CharField(max_length=100, blank=False)
    email = models.EmailField(blank=False)
    problem_tried = models.IntegerField(default = 0)
    problem_solved = models.IntegerField(default = 0)

    def __str__(self):
        return self.username
'''
#this is should be the main model, userSignup fields need to add in it
class Profile(models.Model):
    user_id = models.ForeignKey(UserSignUp, on_delete = models.CASCADE)
    institute = Models.CharField(max_length = 100)
    photo = Models.ImageField(upload_to = path_to_save, default = 'media/default_img.jpg')
    problem_solved = ArrayField(models.CharField())
    problem_unsolved = ArrayField(models.CharField())
'''

hoj/problems/forms.py
from ckeditor.fields import RichTextFormField

from django import forms
from submission.models import Submission

class SubmitForm(forms.ModelForm):
    class Meta:
        model = Submission
        fields = ('language', 'code')

hoj/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import UserSignup


class SignUpForm(UserCreationForm):
    full_name = forms.CharField(max_length=100)
    email = forms.EmailField()

    class Meta:
        model = UserSignup
        fields = UserCreationForm.Meta.fields + ('full_name', 'email',)

hoj/problems/views.py
from django.shortcuts import render, redirect

from .models import Problem
from submission.models import Submission
from .forms import SubmitForm
from Judge_dir.judge import judging

#To view all problems
def problem_list(request):
    problems = Problem.objects.all().order_by('id')
    context = {'problems' : problems}    
    return render(request, 'problems.html', context)

def problem_id(request, pid):
    if request.method == 'POST':
        form = SubmitForm(request.POST, request.FILES)  
        if form.is_valid():
            code = form.save(commit = False) #variable name need to change
            code.user_id = request.user
            problem = Problem.objects.get(id=pid)
            problem.no_of_submissions += 1
            code.problem_id = problem
            code.save() #save the model before judging with default values
			#need to redirect to current submission page (not implemented)
            
            if code.language == 'Python': #Time limit for different language
                time = problem.time_limit[1]
            else:
                time = problem.time_limit[0]
            
            code.verdict, code.time = judging(problem.input_file.path, problem.output_file.path, code.code.path, code.language, time, problem.memory_limit)
            
            if code.verdict == 1:
                problem.no_of_accepted += 1
			#final save after judging
            code.save()
            problem.save()
            return redirect('submit')
    else:
        form = SubmitForm()
        problem = Problem.objects.get(id = pid)
        request.session['pid'] = pid
        context = {'problem' : problem, 'form' : form}
        return render(request, 'problem.html', context)

#To view all submissions, function name need to change
def submit_code(request):
    submission = Submission.objects.all().order_by('-id') #descending order
    context = {'submission' : submission}
    return render(request, 'submit.html', context)

hoj/submission/views.py
from django.shortcuts import render

hoj/user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib import messages

from .forms import SignUpForm


def home(request):
    return render(request, 'home.html')

def about_us(request):
    return render(request, 'about.html')

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            messages.success(request, 'DONE!')
            return redirect('home')
        else:
            messages.warning(request, 'Please correct the errors below!')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', { 'form' : form })

def profile(request):
    return render(request, 'profile.html')

hoj/templates/about.html
{% extends 'base.html' %}
{% block title %}

<style>
.center {
    text-align : center;
    padding : 120px;
}
</style>

<title>About Us</title>

{% endblock %}
{% block content %}
<div class = 'center'>
    <h1>ByteOJ</h1>
    <h2>Developed by</h2>
    <p>Munirul Islam</p>
    <p>Nisab Bin Zahid</p>
    <p>Mehedi Hasan</p>
</div>
{% endblock %}

hoj/templates/base.html
<!-- Header Start -->
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
<style>
.bg{
    background-color: #c3c9a1;
    min-height : 100%;
}
</style>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    {% block title %}
    {% endblock %}
    
  </head>
  <body class ='bg'>



<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'home' %}">ByteOJ.com</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'problem_list' %}">Problems </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href= "{% url 'submit' %}">Submisions</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'about_us' %}">About Us</a>
      </li>
    </ul>
  </div>
<div class="navbar-nav ml-auto">
    {% if user.is_authenticated %}
        <a href = "{% url 'profile' %}" class="nav-item nav-link">{{user.username}}</a>
        <a href = "{% url 'logout' %}?next={{request.path}}" class="nav-item nav-link">Log Out</a>
    {% else %}
        <a href="{% url 'login' %}?next={{request.path}}" class="nav-item nav-link">Sign in</a>
        <a href="{% url 'signup' %}" class="nav-item nav-link">Sign up</a>
    {% endif %}
</div>
</nav>








<div class = 'main_body'>
{% block content %}
{% endblock %}
</div>











    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  </body>
</html>

hoj/templates/home.html
{% extends 'base.html' %}
{% block title %}
<style>
.homebar {
    padding : 200px;
}
</style>
<title>Byte OJ</title>
{% endblock %}
{% block content %}
<h1 align = 'center' class = 'homebar'><font color='green'>Welcome to ByteOJ</font></h1>
	
{% endblock %}

hoj/templates/login.html
{% extends 'base.html' %}
{% block title %}
<title>Login</title>
{% endblock %}
{% block content %}
<style type="text/css">
  .login-form {
    width: 340px;
      margin: 50px auto;
  }
    .login-form form {
      margin-bottom: 15px;
        background: #f7f7f7;
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        padding: 30px;
    }
    .login-form h2 {
        margin: 0 0 15px;
    }
    .form-control, .btn {
        min-height: 38px;
        border-radius: 2px;
    }
    .btn {        
        font-size: 15px;
        font-weight: bold;
    }
</style>
<div class="login-form">

<form method="post">
    <h2 class="text-center">Login</h2>
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit" class="btn btn-primary">Login</button>
</form>
</div>
{% endblock %}

hoj/templates/problem.html
{% extends 'base.html' %}
{% block title %}
<title>{{problem.title}}</title>
{% endblock %}
{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }
    
    .head_text {
        color: white;
    }
    
    .card {
        box-shadow: 0 0px 0px #E3E7EB;
    }
</style>

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-4 left  top">
      <div class="card-body">

<h1>{{problem.id}}. {{problem.title}}</h1>
<pre>Time Limit: {{problem.time_limit.0}}secs   Memory Limit: {{problem.memory_limit}}MB</pre>
<p>{{problem.description | safe}}</p>
<table border = '2'>
    <tr>
        <th>Sample Input</th>
        <th>Sample Output</th>
    <tr>
        <td>{{problem.sample_input | safe}}
        <td>{{problem.sample_output | safe}}
</table>

<!-- Sidebar Widgets Column -->
</div>
</div>
<div class="col-md-4 float-right ">
<div class="card my-4">
        <h5 class="card-header">Submit Your Solution</h5>
    <div class="card-body">
        <form method = 'POST' enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    {% if user.is_authenticated %}
        <button type = 'submit' class="btn btn-primary">Submit Code</button>
    {% else %}
    <p><font color ='red'>Please <a href = '{% url 'login' %}?next={{request.path}}'>Sign in</a> for submit</font></p>
    {% endif %}
    
</form>
    </div>
  </div>
</div>
  </div>
</div>
{% endblock %}

hoj/templates/problems.html
{% extends 'base.html' %}
{% block title %}
<title>Problems</title>
{% endblock %}
{% block content %}
<h2 align = 'center'> Problem Sets</h2>
<table class="table table-sm table-striped table-bordered w-auto" align="center">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Problem Title</th>
      <th scope="col">No. of Submissions</th>
      <th scope="col">No. of Accepted</th>
    </tr>
  </thead>
    <tbody>
    {% for problem in problems %}
        <tr>
          <th scope="row"><a href="/problem/{{problem.id}}"> {{problem.id}}</a></th>
          <td><a href="/problem/{{problem.id}}">{{problem.title}}</a></td>
          <td align = 'center'>{{problem.no_of_submissions}}</td>
          <td align = 'center'>{{problem.no_of_accepted}}</td>
        </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

hoj/templates/profile.html
{% extends 'base.html' %}
{% block title %}
<title>User Profile</title>
{% endblock %}
{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }
    
    .head_text {
        color: white;
    }
    
    .card {
        box-shadow: 0 0px 0px #E3E7EB;
        height : 300px;
    }
</style>

<div class="container">
  <div class="row">


<!-- Sidebar Widgets Column -->
</div>
</div>
<div class="col-md-8 left top ">
<div class="card my-4">
        <h5 class="card-header">Profile</h5>
    <div class="card-body">
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Username</th>
      <th scope="col">Fullname</th>
      <th scope="col">Email</th>
      <th scope="col">Problem Tried</th>
      <th scope="col">Problem Solved</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">{{user.id}}</th>
      <td>{{user.username}}</td>
      <td>{{user.full_name}}</td>
      <td>{{user.email}}</td>
      <td>{{user.problem_tried}}</td>
      <td>{{user.problem_solved}}</td>
    </tr>
  </tbody>
</table>
    </div>
  </div>
</div>
  </div>
</div>
{% endblock %}

hoj/templates/signup.html
{% extends 'base.html' %}
{% block title %}
<title>Sign Up</title>
{% endblock %}
{% block content %}

<style type="text/css">
  .login-form {
    width: 340px;
      margin: 10px auto;
  }
    .login-form form {
      margin-bottom: 15px;
        background: #f7f7f7;
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        padding: 30px;
    }
    .login-form h2 {
        margin: 0 0 15px;
    }
    .form-control, .btn {
        min-height: 38px;
        border-radius: 2px;
    }
    .btn {        
        font-size: 15px;
        font-weight: bold;
    }
</style>
<div class="login-form">
{% if messages %}
<ul class="messages">
    {% for message in messages %}
      <li class="{{ message.tags }}">{{ message }}</li>
    {% endfor %}
  </ul>
{% endif %}
<form method="post">
	<h2>Sign up</h2>
	{% csrf_token %}
	{% for field in form %}
	<p>
		{{ field.label_tag }}<br/>
		{{ field }}
        {{field.errors}}
	</p>
	{% endfor %}
	<button type="submit" class="btn btn-primary">Sign up</button>
</form>
{% endblock %}

hoj/templates/submit.html
{% extends 'base.html' %}
{% block title %}
<title>Submission</title>
{% endblock %}
{% block content %}
<h2 align = 'center'> Submissions</h2>
<table class="table table-sm table-striped table-bordered w-auto" align="center">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Submission Time</th>
      <th scope="col">User</th>
      <th scope="col">Problem Title</th>
      <th scope="col">Language</th>
      <th scope="col">Verdict</th>
      <th scope="col">Time</th>
      <th scope="col">Memory</th>
    </tr>
  </thead>
    <tbody>
    {% for sub in submission %}
        <tr>
          <th scope="row">{{sub.id}}</th>
          <td>{{sub.timestamp}}</td>
          <td>{{sub.user_id.username}}</td>
          <td align = 'center'><a href="/problem/{{sub.problem_id.id}}">{{sub.problem_id.title}}</a></td>
          <td align = 'center'>{{sub.language}}</td>
          <td align = 'center'>{{sub.get_verdict_display}}</td>
          <td align = 'center'>{{sub.time}}</td>
          <td align = 'center'>{{sub.memory}}</td>
        </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

hoj/templates/table.html
<html>
<body>
<table class="table table-sm table-striped table-bordered w-auto" align="center">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">Handle</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>Jacob</td>
      <td>Thornton</td>
      <td>@fat</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td colspan="2">Larry the Bird</td>
      <td>@twitter</td>
    </tr>
  </tbody>
</table>

  </body>
</html>